# Generated by Django 4.2.1 on 2023-09-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='todo',
        ),
    ]
